fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

api:
    resource: "../src/Resource/config/api_routing.yaml"
    type: rest
    prefix: /api/{version}
    requirements:
        version: '%api_versions%'
